# Configure.
language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - pypy3
  - pypy
  - 2.7
  - 2.6
sudo: false

# Environment and matrix.
env: TOX_ENV=py
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=lint
      after_success: []
    - python: 3.5
      env: TOX_ENV=docs
      after_success:
        - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 $_
        - openssl aes-256-cbc -d -K "$encrypted_c89fed6a587d_key" -iv "$encrypted_c89fed6a587d_iv" -out docs/key
          < docs/key.enc && ssh-add $_
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
        - export ${!TRAVIS*}
        - tox -e docsV

# Run.
install: pip install tox
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deploy.
deploy:
  provider: pypi
  user: Robpol86
  password:
    secure:
      "aj+Hl25+NbtmKpHcqxxNJhaMmawgzEPdLX+NwxwAZuTrvUCdiMtYhF9qxN0USHIlXSGDNc\
      7ua6nNpYPhjRv7j5YM4uLlK+4Fv/iU+iQcVfy89BS4vlXzUoje6nLIhogsxytb+FjdGZ0PK\
      JzzxfYr0relUjui/gPYmTQoZ1IiT8A="
  on:
    condition: $TRAVIS_PYTHON_VERSION = 3.4
    tags: true
