language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install robpol86-codecov colorclass
  - pip install .

script:
  - python setup.py test
  - python example1.py
  - python example2.py
  - python example3.py

after_success: codecov
