# Configure.
environment:
  PATH: C:\%PYTHON%;C:\%PYTHON%\Scripts;%PATH%
  PYTHON: Python35
  matrix:
    - TOX_ENV: lint
    - TOX_ENV: py35
    - TOX_ENV: py34
    - TOX_ENV: py33
    - TOX_ENV: py27
    - TOX_ENV: py
      PYTHON: Python35-x64
    - TOX_ENV: py
      PYTHON: Python34-x64
    - TOX_ENV: py
      PYTHON: Python33-x64
    - TOX_ENV: py
      PYTHON: Python27-x64

# Run.
install:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1
  - ps: .\enable-desktop
build_script: pip install tox
test_script: tox -e %TOX_ENV%
on_success: IF %TOX_ENV% NEQ lint pip install codecov & codecov

# Post.
# on_finish: https://github.com/Robpol86/terminaltables/issues/30
  #- appveyor PushArtifact test_ascii_table.png https://github.com/Robpol86/terminaltables/issues/30
  #- appveyor PushArtifact test_double_table.png https://github.com/Robpol86/terminaltables/issues/30
  #- appveyor PushArtifact test_single_table.png https://github.com/Robpol86/terminaltables/issues/30
  #- appveyor PushArtifact test_terminal_io.png https://github.com/Robpol86/terminaltables/issues/30
