init:
  - set PATH=C:\Python35-x64;C:\Python35-x64\Scripts;%PATH%

artifacts:
  - path: .coverage

build_script:
  - pip install tox

test_script:
  - tox -e lint,py35,py34,py33,py27,py35x64,py34x64,py33x64,py27x64
