environment:
  COVERALLS_REPO_TOKEN:
    secure: LaT81XUtZpr1jXbx7yYlcmFRSdQmgMzFQGQV5DtstfFdyJbtn+MZm4QjCby/OaHM
  PYTHONIOENCODING: utf-8

  matrix:
    - PYTHON: 'C:\\Python27'
    - PYTHON: 'C:\\Python27-x64'
    - PYTHON: 'C:\\Python33'
    - PYTHON: 'C:\\Python33-x64'
    - PYTHON: 'C:\\Python34'
    - PYTHON: 'C:\\Python34-x64'

install:
  - ps: Start-FileDownload 'https://raw.github.com/pypa/pip/master/contrib/get-pip.py'
  - '%PYTHON%\\python.exe get-pip.py'
  - '%PYTHON%\\Scripts\\easy_install.exe pyyaml'
  - ps: Move-Item .git ..
  - '%PYTHON%\\Scripts\\pip.exe install .'
  - ps: Move-Item ..\\.git .

build_script: '%PYTHON%\\Scripts\\pip.exe install pytest coveralls colorclass'

test_script:
  - '%PYTHON%\\python.exe setup.py test'
  - '%PYTHON%\\python.exe example1.py'
  - '%PYTHON%\\python.exe example2.py'
  - '%PYTHON%\\python.exe -c "import terminaltables; terminaltables.DEFAULT_TERMINAL_WIDTH=80; import example3"'

after_test: 'cmd /C "set TRAVIS_BRANCH=%APPVEYOR_REPO_BRANCH% && %PYTHON%\\Scripts\\coveralls.exe"'
